# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/huawei/barca/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/huawei/barca

PRODUCT_COPY_FILES += \
    vendor/huawei/barca/proprietary/odm/etc/audio/algorithm/algorithm_barca_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/algorithm/algorithm_barca_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/dts/dts_barca_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/dts/dts_barca_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/hissc/mixer_paths_barca.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_paths_barca.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/hissc/mixer_volumes_barca_ce.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_barca_ce.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/hissc/mixer_volumes_barca_cmcciot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_barca_cmcciot.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/hissc/mixer_volumes_barca_gcf.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_barca_gcf.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/hissc/mixer_volumes_barca_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_barca_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/hissc/mixer_volumes_barca_unicomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/mixer_volumes_barca_unicomiot.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/hissc/pop_seq_barca.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/hissc/pop_seq_barca.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/mbdrc/mbdrc_barca_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/mbdrc/mbdrc_barca_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/modem/modem_barca_cmcciot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_barca_cmcciot.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/modem/modem_barca_gcf.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_barca_gcf.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/modem/modem_barca_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_barca_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/modem/modem_barca_unicomiot.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/modem/modem_barca_unicomiot.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/sws_3d_barca_normal.cfg:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_3d_barca_normal.cfg \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/sws_barca_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_barca_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/sws_config.txt:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_config.txt \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/sws_default.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_default.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/sws_lp_config_1.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_lp_config_1.bin \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/sws_lp_config_2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/sws_lp_config_2.bin \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/tws_config.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/tws_config.bin \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/x2b_config_f.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/x2b_config_f.bin \
    vendor/huawei/barca/proprietary/odm/etc/audio/sws/x2b_config_w.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/sws/x2b_config_w.bin \
    vendor/huawei/barca/proprietary/odm/etc/audio/ti/ti_barca_AAC_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/ti/ti_barca_AAC_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/ti/ti_barca_GD_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/ti/ti_barca_GD_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/ti/ti_barca_GK_normal.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/ti/ti_barca_GK_normal.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/ti/ti_default.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/ti/ti_default.xml \
    vendor/huawei/barca/proprietary/odm/etc/audio/tracklogconfig/codectracklog.config:$(TARGET_COPY_OUT_ODM)/etc/audio/tracklogconfig/codectracklog.config \
    vendor/huawei/barca/proprietary/odm/etc/audio/tracklogconfig/soctracklog.config:$(TARGET_COPY_OUT_ODM)/etc/audio/tracklogconfig/soctracklog.config \
    vendor/huawei/barca/proprietary/odm/etc/camera/dcvalidation.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/dcvalidation.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/facedetection/config.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/facedetection/config.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/ippalgoconfig.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/ippalgoconfig.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/ispenhnc/ispenhncalgoconfig.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/ispenhnc/ispenhncalgoconfig.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/mempoolcfg.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/mempoolcfg.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/mmi/config.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/mmi/config.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/pdafvalidation.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/pdafvalidation.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/ppconfig.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/ppconfig.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/smartae/device.config:$(TARGET_COPY_OUT_ODM)/etc/camera/smartae/device.config \
    vendor/huawei/barca/proprietary/odm/etc/camera/smartae/imx376/SmartAE.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/smartae/imx376/SmartAE.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/smartae/imx486/SmartAE.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/smartae/imx486/SmartAE.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/smartae/ov12a10/SmartAE.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/smartae/ov12a10/SmartAE.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/smartae/ov20880/SmartAE.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/smartae/ov20880/SmartAE.xml \
    vendor/huawei/barca/proprietary/odm/etc/camera/tornado/device.config:$(TARGET_COPY_OUT_ODM)/etc/camera/tornado/device.config \
    vendor/huawei/barca/proprietary/odm/etc/camera/tornado/imx376/TornadoI.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/tornado/imx376/TornadoI.ini \
    vendor/huawei/barca/proprietary/odm/etc/camera/tornado/imx486/TornadoI.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/tornado/imx486/TornadoI.ini \
    vendor/huawei/barca/proprietary/odm/etc/camera/tornado/ov12a10/TornadoI.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/tornado/ov12a10/TornadoI.ini \
    vendor/huawei/barca/proprietary/odm/etc/camera/tornado/ov20880/TornadoI.ini:$(TARGET_COPY_OUT_ODM)/etc/camera/tornado/ov20880/TornadoI.ini \
    vendor/huawei/barca/proprietary/odm/etc/camera/videostabilization/config.xml:$(TARGET_COPY_OUT_ODM)/etc/camera/videostabilization/config.xml \
    vendor/huawei/barca/proprietary/odm/etc/firmware/ts/barca-v8r5_focal_pram_8716.img:$(TARGET_COPY_OUT_ODM)/etc/firmware/ts/barca-v8r5_focal_pram_8716.img \
    vendor/huawei/barca/proprietary/odm/etc/firmware/ts/barca-v8r5_fts_baca30140_ctc.img:$(TARGET_COPY_OUT_ODM)/etc/firmware/ts/barca-v8r5_fts_baca30140_ctc.img \
    vendor/huawei/barca/proprietary/odm/etc/firmware/ts/barca-v8r5_novatek_BACA40170_auo.bin:$(TARGET_COPY_OUT_ODM)/etc/firmware/ts/barca-v8r5_novatek_BACA40170_auo.bin \
    vendor/huawei/barca/proprietary/odm/etc/firmware/ts/barca-v8r5_synaptics_BACA281100_tianma_raw.csv:$(TARGET_COPY_OUT_ODM)/etc/firmware/ts/barca-v8r5_synaptics_BACA281100_tianma_raw.csv \
    vendor/huawei/barca/proprietary/odm/etc/firmware/ts/barca-v8r5_synaptics_BACA28110_tianma.img:$(TARGET_COPY_OUT_ODM)/etc/firmware/ts/barca-v8r5_synaptics_BACA28110_tianma.img \
    vendor/huawei/barca/proprietary/odm/etc/firmware/ts/barca-v8r5_synaptics_BACA281300_boe_raw.csv:$(TARGET_COPY_OUT_ODM)/etc/firmware/ts/barca-v8r5_synaptics_BACA281300_boe_raw.csv \
    vendor/huawei/barca/proprietary/odm/etc/firmware/ts/barca-v8r5_synaptics_BACA28130_boe.img:$(TARGET_COPY_OUT_ODM)/etc/firmware/ts/barca-v8r5_synaptics_BACA28130_boe.img \
    vendor/huawei/barca/proprietary/vendor/etc/cfg_bac_al00_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_bac_al00_hisi.ini \
    vendor/huawei/barca/proprietary/vendor/etc/cfg_bac_lx1_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_bac_lx1_hisi.ini \
    vendor/huawei/barca/proprietary/vendor/etc/cfg_bac_lx3_hisi.ini:$(TARGET_COPY_OUT_VENDOR)/etc/cfg_bac_lx3_hisi.ini

PRODUCT_PACKAGES += \
    hwcam.hi6250.BARCA.p.IMX376 \
    hwcam.hi6250.BARCA.p.IMX486HYBIRD \
    hwcam.hi6250.BARCA.p.OV12A10HYBIRD \
    hwcam.hi6250.BARCA.p.OV20880 \
    hwcam.hi6250.BARCA.s.IMX376 \
    hwcam.hi6250.BARCA.s.IMX486HYBIRD \
    hwcam.hi6250.BARCA.s.OV12A10HYBIRD \
    hwcam.hi6250.BARCA.s.OV20880 \
    hwcam.hi6250.m.BARCA
